name: sauce
on:
    push:
      
    pull_request:
      
  jobs:
    CypressTests-Job:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
          run: npm ci
    - name: Install cypress Browsers
          run: npx install cypress
    - name: Cucumber-Tests
          run: npx run test